"""Shared constants for OpenRescue AI."""

EMPTY = 0
FIRE = 1
CIVILIAN = 2
RESCUE_AGENT = 3
DRONE_AGENT = 4
UNKNOWN = -1

ACTION_UP = 0
ACTION_DOWN = 1
ACTION_LEFT = 2
ACTION_RIGHT = 3

ACTION_NAMES = {
    ACTION_UP: "up",
    ACTION_DOWN: "down",
    ACTION_LEFT: "left",
    ACTION_RIGHT: "right",
}

DEFAULT_GRID_SIZE = 10
DEFAULT_MAX_STEPS = 200
DEFAULT_FIRE_SPREAD_PROBABILITY = 0.10
DEFAULT_FIRE_SPREAD_INTERVAL = 5
DEFAULT_AGENT_VISION_RANGE = 2
DEFAULT_DRONE_VISION_RANGE = 1

